name: 'bar'
description: 'Bar.'
inputs:
  param1:
    description: 'The first parameter.'
    required: true

  param2:
    description: 'The second parameter.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Do bar stuff
      shell: bash
      run: |
        echo ${{ inputs.param1 }} bar ${{ inputs.param2 }}
